version: '3.8'

services:
  stream-api:
    container_name: stream-api
    platform: linux/amd64
    build:
      dockerfile: api/Dockerfile
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - elasticsearch
    restart: always
  stream-app:
    container_name: stream-app
    platform: linux/amd64
    build:
      dockerfile: app/Dockerfile
      context: .
    ports:
      - "80:80"
    depends_on:
      - stream-api
    restart: always
  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - cluster.name=es-docker-cluster
      - node.name=es-node
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    restart: always

  kibana:
    image: kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
    restart: always
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    restart: always

networks:
  default:
    name: stream
volumes:
  es_data:
    driver: local
  kafka_data:
    driver: local