spring:
  kafka:
    listener:
      ack-mode: manual
    consumer:
      bootstrap-servers: kafka:9092
      group-id: stream-app
      auto-offset-reset: earliest
  elasticsearch:
    uris: http://elasticsearch:9200
server:
  port: 8089
  servlet:
    context-path: /api