name: Build and Deploy Stream Application

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/api:${{ github.ref_name }} -f api/Dockerfile .
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/producer:${{ github.ref_name }} -f producer/Dockerfile .
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/app:${{ github.ref_name }} -f app/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Push Docker images to registry
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/api:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/producer:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/app:${{ github.ref_name }}

        env:
          CI: true