name: Build and Deploy (Inprogress)

on:
 push:
    branches:
      - main

jobs:
 build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build api
      run: ./gradlew build
      working-directory: api

    - name: Build producer
      run: ./gradlew build
      working-directory: producer

    - name: Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache YARN packages
      uses: actions/cache@v3
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-node

    - name: Build App
      run: yarn install --frozen-lockfile && yarn build
      working-directory: app

    - name: Deploy to server
      run: |
        # Add your deployment commands here
      env:
        CI: true
