name: Build and Deploy stream application

on:
  push:
    branches:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build api
        run: ./gradlew build
        working-directory: api

      - name: Build Display info
        run: pwd && ls -l

      - name: Build Docker Image for api
        run: docker build -t "${{ secrets.DOCKER_REGISTRY }}"/api:${{ github.ref_name }} -f api/Dockerfile .

      - name: Build producer
        run: ./gradlew build
        working-directory: producer

      - name: Build Docker Image for producer
        run: docker build -t "${{ secrets.DOCKER_REGISTRY }}"/producer:${{ github.ref_name }} -f producer/Dockerfile .

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache YARN packages
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node

      - name: Build App
        run: yarn install --frozen-lockfile && yarn build
        working-directory: app

      - name: Build Docker Image for App
        run: docker build -t "${{ secrets.DOCKER_REGISTRY }}"/app:${{ github.ref_name }} -f app/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Push Docker images to registry
        run: |
          docker push "${{ secrets.DOCKER_REGISTRY }}"/api:${{ github.ref_name }}
          docker push "${{ secrets.DOCKER_REGISTRY }}"/producer:${{ github.ref_name }}
          docker push "${{ secrets.DOCKER_REGISTRY }}"/app:${{ github.ref_name }}

      - name: Deploy to server
        run: |
          # Add your deployment commands here
        env:
          CI: true