name: CI/CD.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-api:
    name: Build api
    runs-on: ubuntu-latest
    defaults:
      run:
        # Mobile folder working directory.
        working-directory: api
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
  # Mobile folder job.
  build-producer:
    name: Build producer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: producer
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
